/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal;

import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author levy
 */
public class Client extends javax.swing.JFrame {

    /**
     * Creates new form Client
     */
    public Client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtvanban = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmahoa = new javax.swing.JTextField();
        btngui = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtkhoa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txttrave = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtvanban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvanbanActionPerformed(evt);
            }
        });

        jLabel1.setText("Văn bản ");

        jLabel2.setText("Văn bản sau khi mã hóa:");

        btngui.setText("Gửi");
        btngui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguiActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");

        jLabel3.setText("Khóa");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("CLIENT");

        jLabel5.setText("Server trả về:");

        txttrave.setColumns(20);
        txttrave.setRows(5);
        jScrollPane1.setViewportView(txttrave);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtmahoa, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(51, 51, 51)
                                    .addComponent(txtvanban, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel2))))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(352, 352, 352)
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(361, 361, 361)
                            .addComponent(btnThoat))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(353, 353, 353)
                            .addComponent(btngui))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel5))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtvanban, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btngui)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtmahoa, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btnThoat)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String mahoa(String vanban, int khoa){
       
        int n=vanban.length();
        int sd,sc;
        sd=khoa;
        String kq="";
        sc=(n/sd)+1;
        char hr[][]=new char[sd][sc];
        int c,d;
        c=0;d=0;
        int sodu=n%sd;
        for (int i=0;i<n;i++){
           hr[d][c]=vanban.charAt(i);
           d++;
           if(d==khoa){
               c++;
               d=0;
           }
        }
        
        int sokytu=sc;
        for (int i=0;i<sd;i++){
//            if (i>=sodu) sokytu=sc-1;
            for (int j=0;j<sokytu;j++){
                kq=kq+hr[i][j];
            }
        }return kq;
    }
    public static int isNumber(String str) { 
        try {  
          int khoa =Integer.parseInt(str);  
          return khoa;
        } catch(NumberFormatException e){  
          return -1;  
        }  
    }

    private void btnguiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguiActionPerformed
        // TODO add your handling code here:
        try{
            DatagramSocket client = new DatagramSocket();
            String vanban=(txtvanban.getText()).trim();
            String khoa = (txtkhoa.getText()).trim();
            int KhoaClient=0;
            if (khoa.length()==0 || vanban.length()==0){
                System.out.println("Nhập văn bản ...");
                JOptionPane.showMessageDialog(null,"Mời bạn nhập văn bản!!!");
            }else{
                byte[] sendData=new byte[1024];
                byte[] sendKhoa = new byte[1024];
                if (isNumber(khoa)==-1)
                    JOptionPane.showMessageDialog(null,"Khóa phải là một số!!!");
                else if (isNumber(khoa)<=0){
                    JOptionPane.showMessageDialog(null,"Khóa phải là một số lớn hơn 0!!!");
                }else{
                    KhoaClient=isNumber(khoa);

                    //khai bao dia chi may server
                    InetAddress add = InetAddress.getByName("localhost");
                    int cong= 9999;

                    //ma hoa van ban

                    vanban=mahoa(vanban,KhoaClient);
                    System.out.println(vanban);
                    txtmahoa.setText(vanban);
                    String chuoi=vanban+"/"+khoa;
                    //chuyen doi du lieu thanh Byte de gui len Server
                    sendData = chuoi.getBytes();        
                    int length =chuoi.length();

                    System.out.println("chuyen doi thành công");
                    txtvanban.setEnabled(false);
                    txtkhoa.setEnabled(false);
                    btngui.setEnabled(false);


                    //packet gui du lieu len server
                    //packet luon co 4 tham so ( mảng byte cần gửi, chiều dài dữ liệu cần gửi, địa chỉ server, địa cổng server)
                    DatagramPacket packetgui=new DatagramPacket(sendData,length,add,cong);
                    client.send(packetgui);
                    System.out.println("Gửi thành công");

                    //khai bao packet nhan du lieu
                    byte[] receiveData=new byte[1024];
                    DatagramPacket packetnhan = new DatagramPacket(receiveData, receiveData.length,add, cong);
                    client.receive(packetnhan);
                    String Data = new String(packetnhan.getData(), 0, packetnhan.getLength());
                    txttrave.setText(Data);
                    client.close();
                }
            }

        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnguiActionPerformed

    private void txtvanbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvanbanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvanbanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btngui;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtkhoa;
    private javax.swing.JTextField txtmahoa;
    private javax.swing.JTextArea txttrave;
    private javax.swing.JTextField txtvanban;
    // End of variables declaration//GEN-END:variables
}
